# Generated by Django 2.0.5 on 2018-05-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_matricol', models.IntegerField()),
                ('materie', models.CharField(max_length=50)),
                ('nota', models.IntegerField()),
            ],
        ),
    ]
